spring:
  application:
    name: auth

  config:
    import: optional:classpath:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/course_platform_db
    username: ${ENV_MYSQL_USER}
    password: ${ENV_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

    fetch-registry: true
    register-with-eureka: true